import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
import joblib
import os

# 1. Prepare your data
# This is dummy data. In a real scenario, you would have a much larger and diverse dataset.
# The 'symptoms' column should contain descriptions of symptoms,
# and 'diagnosis' should contain the corresponding medical condition.
data = {
    'symptoms': [
        "I have a fever, cough, and body aches.",
        "Experiencing sore throat and runny nose.",
        "Severe headache, stiff neck, and light sensitivity.",
        "Shortness of breath, chest pain, and cough with phlegm.",
        "Itchy skin, rash, and sneezing.",
        "Nausea, vomiting, and diarrhea after eating.",
        "Throbbing headache with nausea and sensitivity to light.",
        "Wheezing, shortness of breath, and chest tightness.",
        "Chest pain radiating to my arm.",
        "Sudden weakness on one side, trouble speaking.",
        "Increased thirst, frequent urination, and fatigue.",
        "Palpitations, dizziness, and fear.",
        "Persistent sadness, loss of interest in activities.",
        "Painful urination and frequent urges.",
        "Sudden pain in lower right abdomen, nausea.",
        "Persistent cough with mucus, chest discomfort.",
        "Red eyes, itchiness, and discharge.",
        "Abdominal cramps, vomiting, and diarrhea.",
        "Often no symptoms, but sometimes headache.",
        "Fatigue, weight gain, dry skin.",
        "Severe pain in my side, nausea, vomiting.",
        "Extreme fatigue, sore throat, fever.",
        "Ear pain, difficulty hearing.",
        "Facial pressure, stuffy nose, cough.",
        "Pain, swelling, bruising in ankle.",
        "Sore throat, difficulty swallowing, fever.",
        "Dizziness, nausea, imbalance.",
        "Red, scaly skin patches, itching.",
        "Itchy, red, dry skin, rashes.",
        "Itchy rash, redness, swelling.",
        "Intense itching at night, tiny burrows.",
        "Ring-shaped rash, redness, itching.",
        "Itchy blisters, fever, fatigue.",
        "Fever, cough, runny nose, red rash.",
        "Fever, swollen salivary glands.",
        "Mild fever, rash, swollen glands.",
        "Severe coughing fits, 'whooping' sound.",
        "Muscle spasms, jaw cramping.",
        "Fever, fatigue, headache, stiff neck.",
        "Sore throat, fever, thick coating.",
        "Fever, chills, sweating, headache.",
        "High fever, weakness, stomach pain.",
        "Severe watery diarrhea, vomiting.",
        "High fever, headache, joint pain, rash.",
        "Fever, rash, joint pain, red eyes.",
        "Fever, severe headache, muscle pain.",
        "Cough, chest pain, weight loss.",
        "Fever, fatigue, swollen lymph nodes, rash.",
        "Fatigue, nausea, abdominal pain, jaundice.",
        "Painful urination, abnormal discharge.",
        "Painless sore, rash, swollen lymph nodes.",
        "Abnormal discharge, painful urination.",
        "Oral or genital sores, itching.",
        "Genital warts, often no symptoms.",
        "Increased thirst, frequent urination.",
        "No symptoms, sometimes headache, nosebleeds.",
        "Shakiness, dizziness, sweating, hunger.",
        "Weight loss, nervousness, rapid heartbeat.",
        "Severe pain in big toe, swelling, redness.",
        "Joint pain and swelling, stiffness.",
        "Joint pain, stiffness, loss of flexibility.",
        "Fatigue, joint pain, rash, fever.",
        "Fatigue, numbness, vision problems.",
        "Tremor, slow movement, stiffness.",
        "Memory loss, confusion, difficulty with tasks.",
        "Cloudy vision, poor night vision.",
        "Loss of peripheral vision, eye pain.",
        "Blurred central vision.",
        "Blurred vision, floaters, dark spots.",
        "Fatigue, swelling in legs, nausea.",
        "Fatigue, nausea, jaundice, swelling.",
        "Sudden pain in upper right abdomen, nausea.",
        "Upper abdominal pain, nausea, fever.",
        "Abdominal pain, bloating, diarrhea.",
        "Abdominal pain, diarrhea, weight loss.",
        "Abdominal pain, bloody diarrhea, weight loss.",
        "Diarrhea, abdominal pain, bloating.",
        "Fatigue, weakness, pale skin, shortness of breath.",
        "Fatigue, frequent infections, easy bruising.",
        "Swollen lymph nodes, fever, night sweats.",
        "Lump in breast, skin dimpling.",
        "Persistent cough, chest pain, weight loss.",
        "Change in bowel habits, blood in stool.",
        "Difficulty urinating, weak urine stream.",
        "New mole or change in existing mole.",
        "Bloating, pelvic pain, difficulty eating.",
        "Vaginal bleeding, pelvic pain.",
        "Lump in neck, difficulty swallowing.",
        "Headaches, seizures, vision changes.",
        "Tremor, slow movement, posture changes.",
        "Involuntary jerking movements, cognitive decline.",
        "Persistent cough, lung infections, poor weight gain.",
        "Fatigue, pain crises, swelling in hands and feet.",
        "Fatigue, weakness, pale skin, slow growth.",
        "Prolonged bleeding, easy bruising.",
        "Distinct facial appearance, intellectual disability.",
        "Challenges with social interaction, repetitive behaviors.",
        "Inattention, hyperactivity, impulsivity.",
        "Mood swings (mania and depression).",
        "Hallucinations, delusions, disorganized thinking.",
        "Obsessions (unwanted thoughts) and compulsions (behaviors).",
        "Flashbacks, nightmares, severe anxiety.",
        "Extreme restriction of food intake.",
        "Binge eating followed by purging.",
        "Recurrent episodes of eating large quantities of food.",
        "Instability in relationships, self-image.",
        "Excessive daytime sleepiness, sudden loss of muscle tone.",
        "Difficulty falling or staying asleep.",
        "Snoring, pauses in breathing during sleep.",
        "Uncontrollable urge to move legs at night.",
        "Severe fatigue not improved by rest.",
        "Widespread musculoskeletal pain, fatigue.",
        "Fever, headache, fatigue, skin rash.",
        "Fever, headache, rash, nausea.",
        "Fever, rash, joint pain, red eyes, muscle pain.",
        "Fever, severe joint pain, headache.",
        "Fever, severe headache, muscle pain, bleeding.",
        "Fever, cough, shortness of breath.",
        "High fever, body aches, dry cough.",
        "Fatigue, fever, muscle aches, shortness of breath.",
        "Nausea, vomiting, diarrhea, stomach cramps.",
        "Severe watery diarrhea, vomiting, fever.",
        "Diarrhea, gas, greasy stools.",
        "Diarrhea (often bloody), stomach pain.",
        "Watery diarrhea, stomach cramps.",
        "Rash, itchy skin, fever, chills.",
        "Itching and rash, abdominal pain.",
        "Cough, fever, abdominal pain, worms in stool.",
        "Nausea, weakness, abdominal pain.",
        "Anal itching at night, restless sleep.",
        "Muscle pain, fever, swelling around eyes.",
        "Fever, muscle aches, nausea, stiff neck.",
        "Difficulty swallowing, facial weakness, paralysis.",
        "Boils, impetigo, cellulitis, fever.",
        "Sore throat, fever, red tonsils.",
        "Red, swollen, tender skin, fever.",
        "Red sores that rupture and ooze.",
        "Small red bumps around hair follicles.",
        "Red, painful, pus-filled lump.",
        "Cluster of boils, connected infection.",
        "Skin infections like pimples or boils.",
        "Itchy, scaly rash between toes.",
        "Itchy, red, ring-shaped rash in groin.",
        "Thickened, discolored, brittle nails.",
        "Itching, burning, redness, white discharge.",
        "White lesions on tongue, soreness.",
        "Painful sores inside the mouth.",
        "Fluid-filled blisters on or around lips.",
        "Inflamed, red, swollen gums.",
        "Swollen, tender, bleeding gums, loose teeth.",
        "Toothache, sensitivity to hot/cold.",
        "Severe, persistent toothache, fever.",
        "Jaw pain, clicking sound in jaw.",
        "Burning pain in chest after eating.",
        "Upper abdominal pain, nausea, bloating.",
        "Burning stomach pain, bloating, heartburn.",
        "Severe pain in upper right abdomen.",
        "Fatigue, nausea, abdominal pain, dark urine.",
        "Fatigue, nausea, jaundice, confusion.",
        "Abdominal pain (lower left), fever.",
        "Pain, itching, bleeding during bowel movements.",
        "Pain during bowel movements, bleeding.",
        "Infrequent bowel movements, straining.",
        "Loose, watery stools, abdominal cramps.",
        "Upper abdominal discomfort after eating.",
        "Diarrhea, abdominal pain, bloating, rash.",
        "Abdominal cramps, bloating, diarrhea after dairy.",
        "Hives, swelling, vomiting, difficulty breathing.",
        "Nausea, vomiting, diarrhea, fever.",
        "Sudden pain around navel to lower right abdomen.",
        "Abdominal pain, cramping, bloating, diarrhea.",
        "Abdominal pain, diarrhea, weight loss, fever.",
        "Abdominal pain, bloody diarrhea, weight loss.",
        "Nausea, vomiting, diarrhea, fever.",
        "Painful urination, frequent urge, cloudy urine.",
        "Back or side pain, high fever, chills.",
        "Severe pain in side and back, blood in urine.",
        "Frequent and sudden urge to urinate.",
        "Chronic bladder pain and pressure.",
        "Cough, fever, chills, shortness of breath, chest pain.",
        "Cough with mucus, fatigue, chest discomfort.",
        "Shortness of breath, wheezing, cough.",
        "Shortness of breath, chronic cough, wheezing.",
        "Shortness of breath, chronic cough.",
        "Daily cough and mucus for 2 years.",
        "Sudden shortness of breath, chest pain.",
        "Sharp chest pain with breathing, cough.",
        "Loud snoring, pauses in breathing, daytime sleepiness.",
        "Difficulty falling or staying asleep.",
        "Excessive daytime sleepiness, sleep attacks.",
        "Uncomfortable leg sensations, urge to move.",
        "Excessive daytime sleepiness or long sleep.",
        "Fatigue, weakness, pale skin, cold hands/feet.",
        "Fatigue, weakness, tingling in hands/feet.",
        "Fatigue, pain episodes, swelling of hands and feet.",
        "Fatigue, weakness, pale skin, slow growth.",
        "Prolonged bleeding after injury, joint pain.",
        "Fatigue, fever, easy bruising, swollen lymph nodes.",
        "Painless swollen lymph nodes, fever, night sweats.",
        "Bone pain, fatigue, frequent infections.",
        "Fatigue, shortness of breath, easy bruising.",
        "Fatigue, frequent infections, easy bruising.",
        "Headache, dizziness, fatigue, shortness of breath.",
        "Dizziness, lightheadedness, fainting.",
        "Chest pain, shortness of breath, fatigue.",
        "Chest pain radiating to arm, shortness of breath.",
        "Shortness of breath, fatigue, leg swelling.",
        "Palpitations, racing heartbeat, dizziness.",
        "Sudden numbness or weakness, confusion.",
        "Mini-stroke; temporary stroke-like symptoms.",
        "Leg pain with walking, coldness in foot.",
        "Swelling in leg, pain, redness, warmth.",
        "Sudden shortness of breath, chest pain, cough.",
        "No symptoms until rupture; severe headache (brain).",
        "Enlarged, twisted veins, aching legs.",
        "Joint pain, stiffness, grating sensation.",
        "Tender, warm, swollen joints, morning stiffness.",
        "Sudden, severe attacks of pain in big toe.",
        "Arthritis-like symptoms with crystals.",
        "Pain and swelling around a joint.",
        "Pain, tenderness, mild swelling of a tendon.",
        "Stretching or tearing of ligaments.",
        "Stretching or tearing of muscle or tendon.",
        "Break in a bone.",
        "Bones in a joint forced out of alignment.",
        "Headache, dizziness, confusion, memory problems.",
        "Persistent symptoms after concussion (headache, dizziness).",
        "Sudden, brief episodes of dizziness with head movement.",
        "Recurrent vertigo, hearing loss, tinnitus.",
        "Ringing or buzzing in the ears.",
        "Gradual age-related hearing loss.",
        "Ear pain, itching, redness, discharge.",
        "Muffled hearing, fullness in ear, popping.",
        "Stuffy nose, reduced sense of smell.",
        "Difficulty breathing through one nostril.",
        "Bleeding from the nose.",
        "Pain or scratchiness in throat, difficulty swallowing.",
        "Hoarse voice, loss of voice, sore throat.",
        "Sore throat, difficulty swallowing, fever.",
        "Sudden sore throat, painful swallowing, fever.",
        "Creamy white lesions on tongue, soreness.",
        "Small, painful sores inside the mouth.",
        "Fluid-filled blisters on or around the lips.",
        "Inflamed, red, swollen gums that bleed.",
        "Swollen, tender, bleeding gums, loose teeth.",
        "Toothache, sensitivity to hot/cold, holes.",
        "Severe, persistent toothache, fever, swelling.",
        "Jaw pain, clicking or popping sound.",
        "Burning pain in chest after eating, regurgitation.",
        "Upper abdominal pain, nausea, bloating.",
        "Burning stomach pain, bloating, heartburn.",
        "Severe pain in upper right abdomen, nausea, fever.",
        "Fatigue, nausea, abdominal pain, dark urine.",
        "Fatigue, nausea, jaundice, swelling, confusion.",
        "Abdominal pain (lower left), fever, nausea.",
        "Pain, itching, bleeding during bowel movements.",
        "Pain during bowel movements, bleeding, itching.",
        "Infrequent bowel movements, straining, hard stools.",
        "Loose, watery stools, abdominal cramps, nausea.",
        "Upper abdominal discomfort after eating, bloating.",
        "Diarrhea, abdominal pain, bloating, rash.",
        "Abdominal cramps, bloating, gas after dairy.",
        "Hives, swelling, vomiting, difficulty breathing.",
        "Nausea, vomiting, diarrhea, abdominal cramps.",
        "Sudden pain around navel to lower right abdomen, nausea.",
        "Abdominal pain, cramping, bloating, diarrhea or constipation.",
        "Abdominal pain, diarrhea, weight loss, fatigue, fever.",
        "Abdominal pain, bloody diarrhea, weight loss, fatigue.",
        "Nausea, vomiting, diarrhea, abdominal cramps, fever."
    ],
    'diagnosis': [
        "Flu",
        "Common Cold",
        "Meningitis",
        "Pneumonia",
        "Allergies",
        "Food Poisoning",
        "Migraine",
        "Asthma Attack",
        "Heart Attack",
        "Stroke",
        "Diabetes (Type 2)",
        "Anxiety Attack",
        "Depression",
        "Urinary Tract Infection (UTI)",
        "Appendicitis",
        "Bronchitis",
        "Conjunctivitis (Pink Eye)",
        "Gastroenteritis",
        "Hypertension (High Blood Pressure)",
        "Hypothyroidism",
        "Kidney Stones",
        "Mononucleosis",
        "Otitis Media (Ear Infection)",
        "Sinusitis",
        "Sprain/Strain",
        "Tonsillitis",
        "Vertigo",
        "Psoriasis",
        "Eczema",
        "Dermatitis",
        "Scabies",
        "Ringworm",
        "Chickenpox",
        "Measles",
        "Mumps",
        "Rubella (German Measles)",
        "Whooping Cough (Pertussis)",
        "Tetanus",
        "Polio",
        "Diphtheria",
        "Malaria",
        "Typhoid Fever",
        "Cholera",
        "Dengue Fever",
        "Zika Virus",
        "Ebola Virus Disease",
        "Tuberculosis (TB)",
        "HIV/AIDS",
        "Hepatitis B",
        "Gonorrhea",
        "Syphilis",
        "Chlamydia",
        "Herpes",
        "HPV (Human Papillomavirus)",
        "Diabetes Mellitus",
        "Hypertension",
        "Hypoglycemia",
        "Hyperthyroidism",
        "Gout",
        "Rheumatoid Arthritis",
        "Osteoarthritis",
        "Lupus",
        "Multiple Sclerosis (MS)",
        "Parkinson's Disease",
        "Alzheimer's Disease",
        "Cataracts",
        "Glaucoma",
        "Macular Degeneration",
        "Diabetic Retinopathy",
        "Kidney Failure",
        "Liver Cirrhosis",
        "Gallstones",
        "Pancreatitis",
        "Irritable Bowel Syndrome (IBS)",
        "Crohn's Disease",
        "Ulcerative Colitis",
        "Celiac Disease",
        "Anemia",
        "Leukemia",
        "Lymphoma",
        "Breast Cancer",
        "Lung Cancer",
        "Colon Cancer",
        "Prostate Cancer",
        "Skin Cancer",
        "Ovarian Cancer",
        "Cervical Cancer",
        "Thyroid Cancer",
        "Brain Tumor",
        "Parkinson's Disease",
        "Huntington's Disease",
        "Cystic Fibrosis",
        "Sickle Cell Anemia",
        "Thalassemia",
        "Hemophilia",
        "Down Syndrome",
        "Autism Spectrum Disorder",
        "ADHD (Attention-Deficit/Hyperactivity Disorder)",
        "Bipolar Disorder",
        "Schizophrenia",
        "Obsessive-Compulsive Disorder (OCD)",
        "Post-Traumatic Stress Disorder (PTSD)",
        "Anorexia Nervosa",
        "Bulimia Nervosa",
        "Binge Eating Disorder",
        "Borderline Personality Disorder",
        "Narcolepsy",
        "Insomnia",
        "Sleep Apnea",
        "Restless Legs Syndrome (RLS)",
        "Chronic Fatigue Syndrome (CFS)",
        "Fibromyalgia",
        "Lyme Disease",
        "Rocky Mountain Spotted Fever",
        "Zika Virus Infection",
        "Chikungunya Fever",
        "Ebola Virus Disease",
        "Middle East Respiratory Syndrome (MERS)",
        "Severe Acute Respiratory Syndrome (SARS)",
        "Hantavirus Pulmonary Syndrome (HPS)",
        "Norovirus Infection",
        "Rotavirus Infection",
        "Giardiasis",
        "Amebiasis",
        "Cryptosporidiosis",
        "Schistosomiasis",
        "Hookworm Infection",
        "Roundworm Infection",
        "Tapeworm Infection",
        "Pinworm Infection",
        "Trichinosis",
        "Listeriosis",
        "Botulism",
        "Staph Infection",
        "Strep Throat",
        "Cellulitis",
        "Impetigo",
        "Folliculitis",
        "Boils (Furuncles)",
        "Carbuncles",
        "MRSA Infection",
        "Athlete's Foot (Tinea Pedis)",
        "Jock Itch (Tinea Cruris)",
        "Toenail Fungus (Onychomycosis)",
        "Candidiasis (Yeast Infection)",
        "Thrush (Oral Candidiasis)",
        "Ringworm (Tinea Corporis)",
        "Pityriasis Rosea",
        "Shingles (Herpes Zoster)",
        "Cold Sores (Herpes Simplex Labialis)",
        "Genital Herpes (Herpes Simplex Virus)",
        "Genital Warts (HPV)",
        "Chancroid",
        "Lymphogranuloma Venereum (LGV)",
        "Granuloma Inguinale (Donovanosis)",
        "Pelvic Inflammatory Disease (PID)",
        "Epididymitis",
        "Orchitis",
        "Prostatitis",
        "Benign Prostatic Hyperplasia (BPH)",
        "Erectile Dysfunction (ED)",
        "Peyronie's Disease",
        "Priapism",
        "Testicular Torsion",
        "Varicocele",
        "Hydrocele",
        "Spermatocele",
        "Breast Cysts",
        "Fibrocystic Breasts",
        "Mastitis",
        "Endometriosis",
        "Uterine Fibroids",
        "Ovarian Cysts",
        "Polycystic Ovary Syndrome (PCOS)",
        "Premenstrual Syndrome (PMS)",
        "Premenstrual Dysphoric Disorder (PMDD)",
        "Menopause",
        "Perimenopause",
        "Osteoporosis",
        "Arthritis (general)",
        "Bursitis",
        "Tendinitis",
        "Gout (Acute Attack)",
        "Lupus (Systemic Lupus Erythematosus)",
        "Scleroderma",
        "Sjögren's Syndrome",
        "Ankylosing Spondylitis",
        "Psoriatic Arthritis",
        "Rheumatic Fever",
        "Osteomyelitis",
        "Septic Arthritis",
        "Spinal Stenosis",
        "Herniated Disc",
        "Sciatica",
        "Pinched Nerve",
        "Carpal Tunnel Syndrome",
        "Tennis Elbow (Lateral Epicondylitis)",
        "Golfer's Elbow (Medial Epicondylitis)",
        "Rotator Cuff Tear",
        "Bursitis (Shoulder)",
        "Frozen Shoulder (Adhesive Capsulitis)",
        "Plantar Fasciitis",
        "Achilles Tendinitis",
        "Bunions",
        "Hammer Toe",
        "Morton's Neuroma",
        "Stress Fracture",
        "Shin Splints",
        "Concussion",
        "Post-Concussion Syndrome",
        "Vertigo (BPPV)",
        "Meniere's Disease",
        "Tinnitus",
        "Hearing Loss (Presbycusis)",
        "Otitis Externa (Swimmer's Ear)",
        "Eustachian Tube Dysfunction",
        "Nasal Polyps",
        "Deviated Septum",
        "Epistaxis (Nosebleed)",
        "Sore Throat (Pharyngitis)",
        "Laryngitis",
        "Tonsillitis (Bacterial/Viral)",
        "Strep Throat (Bacterial Pharyngitis)",
        "Oral Thrush (Candidiasis)",
        "Canker Sore (Aphthous Ulcer)",
        "Cold Sore (Herpes Simplex Virus 1)",
        "Gingivitis",
        "Periodontitis",
        "Cavity (Dental Caries)",
        "Abscessed Tooth",
        "Temporomandibular Joint (TMJ) Disorder)",
        "Heartburn (GERD)",
        "Gastritis",
        "Peptic Ulcer",
        "Cholecystitis (Gallbladder Inflammation)",
        "Hepatitis (Viral)",
        "Cirrhosis",
        "Diverticulitis",
        "Hemorrhoids",
        "Anal Fissure",
        "Constipation",
        "Diarrhea",
        "Indigestion (Dyspepsia)",
        "Celiac Disease (Gluten Intolerance)",
        "Lactose Intolerance",
        "Food Allergy",
        "Food Poisoning",
        "Appendicitis",
        "Irritable Bowel Syndrome (IBS)",
        "Crohn's Disease",
        "Ulcerative Colitis",
        "Gastroenteritis (Stomach Flu)",
        "Urinary Tract Infection (UTI)",
        "Kidney Infection (Pyelonephritis)",
        "Kidney Stones",
        "Overactive Bladder",
        "Interstitial Cystitis (Painful Bladder Syndrome)",
        "Pneumonia (Bacterial/Viral)",
        "Bronchitis (Acute/Chronic)",
        "Asthma",
        "COPD (Chronic Obstructive Pulmonary Disease)",
        "Emphysema",
        "Chronic Bronchitis",
        "Pulmonary Embolism",
        "Pleurisy",
        "Sleep Apnea (Obstructive/Central)",
        "Insomnia (Chronic)",
        "Narcolepsy",
        "Restless Legs Syndrome (RLS)",
        "Hypersomnia",
        "Anemia (Iron Deficiency)",
        "Anemia (Vitamin Deficiency)",
        "Sickle Cell Anemia",
        "Thalassemia",
        "Hemophilia (A/B)",
        "Leukemia (Acute/Chronic)",
        "Lymphoma (Hodgkin/Non-Hodgkin)",
        "Multiple Myeloma",
        "Myelodysplastic Syndromes (MDS)",
        "Aplastic Anemia",
        "Polycythemia Vera",
        "Thrombocytopenia",
        "Hypertension (High Blood Pressure)",
        "Hypotension (Low Blood Pressure)",
        "Coronary Artery Disease (CAD)",
        "Heart Attack (Myocardial Infarction)",
        "Heart Failure (Congestive Heart Failure)",
        "Arrhythmia (Irregular Heartbeat)",
        "Stroke (Ischemic/Hemorrhagic)",
        "Transient Ischemic Attack (TIA)",
        "Peripheral Artery Disease (PAD)",
        "Deep Vein Thrombosis (DVT)",
        "Pulmonary Embolism (PE)",
        "Aneurysm (Brain/Aortic)",
        "Varicose Veins",
        "Arthritis (Osteoarthritis)",
        "Rheumatoid Arthritis",
        "Gout",
        "Pseudogout",
        "Bursitis",
        "Tendinitis",
        "Sprain",
        "Strain",
        "Fracture (Bone)",
        "Dislocation",
        "Concussion",
        "Meningitis (Bacterial/Viral)",
        "Encephalitis",
        "Parkinson's Disease",
        "Alzheimer's Disease",
        "Dementia with Lewy Bodies",
        "Vascular Dementia",
        "Frontotemporal Dementia (FTD)",
        "Huntington's Disease",
        "Multiple Sclerosis (MS)",
        "Amyotrophic Lateral Sclerosis (ALS)",
        "Epilepsy",
        "Stroke",
        "Transient Ischemic Attack (TIA)",
        "Brain Tumor",
        "Hydrocephalus",
        "Spina Bifida",
        "Cerebral Palsy",
        "Tourette Syndrome",
        "Attention-Deficit/Hyperactivity Disorder (ADHD)",
        "Autism Spectrum Disorder (ASD)",
        "Schizophrenia",
        "Bipolar Disorder",
        "Major Depressive Disorder",
        "Generalized Anxiety Disorder (GAD)",
        "Panic Disorder",
        "Social Anxiety Disorder",
        "Obsessive-Compulsive Disorder (OCD)",
        "Post-Traumatic Stress Disorder (PTSD)",
        "Eating Disorders (Anorexia, Bulimia, Binge Eating Disorder)",
        "Borderline Personality Disorder (BPD)",
        "Narcissistic Personality Disorder (NPD)",
        "Antisocial Personality Disorder (ASPD)",
        "Sleep Apnea",
        "Insomnia",
        "Narcolepsy",
        "Restless Legs Syndrome (RLS)",
        "Chronic Fatigue Syndrome (CFS)",
        "Fibromyalgia",
        "Lyme Disease",
        "West Nile Virus",
        "Zika Virus",
        "Dengue Fever",
        "Malaria",
        "Tuberculosis (TB)",
        "HIV/AIDS",
        "Hepatitis (A, B, C)",
        "Influenza (Flu)",
        "Common Cold",
        "Strep Throat",
        "Pneumonia",
        "Bronchitis",
        "Asthma",
        "Allergies (Seasonal)",
        "Food Allergies",
        "Eczema (Atopic Dermatitis)",
        "Psoriasis",
        "Acne",
        "Rosacea",
        "Dermatitis (Contact/Seborrheic)",
        "Hives (Urticaria)",
        "Shingles (Herpes Zoster)",
        "Chickenpox",
        "Measles",
        "Mumps",
        "Rubella (German Measles)",
        "Whooping Cough (Pertussis)",
        "Tetanus",
        "Polio",
        "Diphtheria",
        "Sexually Transmitted Infections (STIs) - General",
        "Chlamydia",
        "Gonorrhea",
        "Syphilis",
        "Herpes Simplex Virus (HSV)",
        "Human Papillomavirus (HPV)",
        "HIV/AIDS",
        "Trichomoniasis",
        "Bacterial Vaginosis (BV)",
        "Yeast Infection (Vaginal Candidiasis)"
    ]
}

df = pd.DataFrame(data)

# 2. Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    df['symptoms'], df['diagnosis'], test_size=0.2, random_state=42
)

# 3. Create a machine learning pipeline
# This pipeline first transforms text data into numerical features (TF-IDF)
# and then uses a Logistic Regression classifier.
pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(stop_words='english')),
    ('classifier', LogisticRegression(max_iter=1000, solver='liblinear')) # Increased max_iter for convergence
])

# 4. Train the model
print("Training the machine learning model...")
pipeline.fit(X_train, y_train)
print("Model training complete.")

# 5. Evaluate the model (optional, but good practice)
# from sklearn.metrics import accuracy_score, classification_report
# y_pred = pipeline.predict(X_test)
# print(f"\nModel Accuracy: {accuracy_score(y_test, y_pred):.2f}")
# print("\nClassification Report:\n", classification_report(y_test, y_pred))

# 6. Save the trained model to a .pkl file
model_filename = 'symptom_classifier_model.pkl'
joblib.dump(pipeline, model_filename)

print(f"\nMachine learning model saved as '{model_filename}' in: {os.getcwd()}")
print("You can now run your coreEfx.txt application, and it will load this model for predictions.")